matrix:
  include:

    - os: osx
      osx_image: xcode6.4 # use the oldest possible version of macOS
      script:
        # skip setup to avoid doctor failure because of old Xcode
        - brew test-bot --skip-setup

    - os: linux
      sudo: required
      services:
        - docker
      before_install:
        - docker build -f docker/Dockerfile -t homebrew-portable .
      script:
        - docker run -e "TRAVIS=$TRAVIS" -e "TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE" -e "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" -e "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" homebrew-portable bash -c 'brew tap --full alyssais/test-bot && (pushd .linuxbrew/Library/Taps/alyssais/homebrew-test-bot; git checkout origin/linux; popd) && brew test-bot'
